#!/usr/bin/env bash

export COMMON_DIR="${SNAP_DATA}"
export COMMON_USER_DIR="${COMMON_DIR}/user-data"
export COMMON_CERTS="${COMMON_DIR}/certs"
export SSH_DIR="${SNAP_USER_DATA}/.ssl"
export SSH_KEY="${SSH_DIR}/id_rsa"
export SSH_PUB_KEY="${COMMON_USER_DIR}/`basename "${SSH_KEY}.pub"`"
