#!/usr/bin/env bash

source "${SNAP}/helper/functions"
source "${SNAP}/helper/variables"

if [[ `amiroot` != "root" ]]; then
    echo "Not root `amiroot`"
    exit 1
fi

readarray -d '' USERS < <(find "${COMMON_USER_DIR}" -maxdepth 1 -type d -not -path "${COMMON_USER_DIR}" -print0)

for USER in "${USERS[@]}"; do
    ssh -i "${SSH_KEY}" \
        -F "${SSH_DIR}" \
        -o BatchMode=yes \
        -o StrictHostKeyChecking=accept-new \
        -o UserKnownHostsFile="${SSH_DIR}/known_hosts" \
    -l `basename "${USER}"` localhost -n -f '/snap/bin/acme-sh --renew-all --force >> ~/.cert-renew'
done
