#!/usr/bin/env bash

CONN_SNAP=`snapctl get --slot :certs snapname`
CONN_UUID=`snapctl get --slot :certs uuid`
CONN_PKEY=`snapctl get --slot :certs pkey`

if [ -z "${CONN_SNAP}" ]; then
    echo "Parameter 'snapname' is missing"
    echo "Are your sure your app supports this plug?"
    exit 1
fi

if [ -z "${CONN_UUID}" ]; then
    echo "Parameter 'uuid' is missing"
    echo "Are your sure your app supports this plug?"
    exit 1
fi

if [ -z "${CONN_PKEY}" ]; then
    echo "Parameter 'pkey' is missing"
    echo "Are your sure your app supports this plug?"
    exit 1
fi

source "${SNAP}/helper/variables"

logger "Connecting from ${CONN_SNAP} (uuid: ${CONN_UUID})."

readarray -d '' CERT_DIRS < <(find "${SNAP_DATA}" -maxdepth 1 -type d -name "certs*" -print0)

for DIR in "${CERT_DIRS[@]}"; do
    logger "${DIR}: `ls ${DIR} | wc -l`"
    if [ `ls ${DIR} | wc -l` -eq 0 ]; then
        chmod 1755 "${DIR}"
        KEY="${DIR}/${CONN_SNAP}_${CONN_UUID}.pub"
        logger "Storing GPG-key to ${KEY}"
        echo -e "${CONN_PKEY}" > "${KEY}"
        chmod 1644 "${KEY}"
        mkdir -m 1777 "${DIR}/encrypted"
        break
    fi
done
