#!/usr/bin/env bash
set -ex

source "${SNAP}/helper/variables"

if [ ! -d "${COMMON_USER_DIR}" ]; then
    mkdir "${COMMON_USER_DIR}"
    chmod 1777 "${COMMON_USER_DIR}"
fi

if [ ! -d "${SSH_DIR}" ]; then
    mkdir "${SSH_DIR}" || (echo "Failed creating ${SSH_DIR}" && exit 1)
fi

if [ ! -f "${SSH_KEY}" ]; then
    $SNAP/usr/bin/ssh-keygen -t rsa \
        -b 4096 -q -f "${SSH_KEY}" -N "" -C "acme-sh@localhost"
    mv "${SSH_KEY}.pub" "${SSH_PUB_KEY}"
    chmod 1644 "${SSH_PUB_KEY}"
fi

